<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $image
 * @property string|null $date
 * @property int|null $viewed
 * @property int|null $user_id
 * @property int|null $category_id
 *
 * @property Category $category
 * @property Comment[] $comments
 * @property User $user
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date'], 'date', 'format'=>'php:Y-m-d'],
            [['date'], 'default', 'value'=>date('Y-m-d')],
            [['title', 'description'], 'string', 'max' => 256],
            [['title'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'image' => Yii::t('app', 'Image'),
            'date' => Yii::t('app', 'Date'),
            'viewed' => Yii::t('app', 'Viewed'),
            'user_id' => Yii::t('app', 'User ID'),
            'category_id' => Yii::t('app', 'Category ID'),
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.pg';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id'=>'catgory_id']);
    }

    public function saveCategory($catgory_id)
    {
        $category = Category::findOne($catgory_id);
        if($category != null)
        {
            $this->link('category', $category);
            return true;
        }
    }

    public function getTag()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('post_tag', ['post_id' => 'id']);
    }

    public function getSelectedTag()
    {
        $selectedTag = $this->getTag()->select('id')->asArray()->all();
        return ArrayHelper::getColumn($selectedTag, 'id');
    }

    public function saveTag($tag)
    {
        if(is_array($tag))
        {
            $this->clearCurrentTag();

            foreach ($this as $tag_id)
            {
                $tag = Tag::findOne($tag_id);
                $this->link('tag', $tag);
            }
        }
    }

    public function clearCurrentTag()
    {
        PostTag::deleteAll(['post_id'=>$this->id]);
    }
}
